### ISSUE TITLE
Trim Animations bug

### ISSUE THREAD

**Issue by DouglasHhhH** [KyonkoYuuki/YaEANOrganizer#3]
Ok so when i trim the animations and load them in xenoviewer they look like this

![image](https://user-images.githubusercontent.com/53399420/62006552-d7021180-b139-11e9-813f-736da6350939.png)

When they are supposed to look like this

![image](https://user-images.githubusercontent.com/53399420/62006553-e2edd380-b139-11e9-9c53-b9e4d70f7565.png)

**Comment by KyonkoYuuki** [comment]
Found the bug and fixed it
