### ISSUE TITLE
Suggestion : Delete Specific Keyframes

### ISSUE THREAD

**Issue by UnleashedGH** [KyonkoYuuki/YaEANOrganizer#4]
The Remove Keyframes feature is awesome, especially with the bone filter.
but i was wondering if it would be possible to implement a feature to delete specific keyframes, say you define a range (ie from Frame 50 to Frame 70) and then delete any keyframe that is in that range from the animation (pos, rot, scale)

**Comment by KyonkoYuuki** [comment]
Good suggestion, will be in the next release.

**Comment by KyonkoYuuki** [comment]
This has been added as of 0.4.10
